// Code generated by MockGen. DO NOT EDIT.
// Source: service_implementation.go
//
// Generated by this command:
//
//	mockgen -source=service_implementation.go -destination=mocks/mock.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	models "bot_story_generator/internal/models"
	context "context"
	reflect "reflect"
	time "time"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockTxManager) BeginTx(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockTxManagerMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockTxManager)(nil).BeginTx), ctx)
}

// CommitTx mocks base method.
func (m *MockTxManager) CommitTx(ctx context.Context, tx pgx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTx", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTx indicates an expected call of CommitTx.
func (mr *MockTxManagerMockRecorder) CommitTx(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTx", reflect.TypeOf((*MockTxManager)(nil).CommitTx), ctx, tx)
}

// RollbackTx mocks base method.
func (m *MockTxManager) RollbackTx(ctx context.Context, tx pgx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTx", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTx indicates an expected call of RollbackTx.
func (mr *MockTxManagerMockRecorder) RollbackTx(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTx", reflect.TypeOf((*MockTxManager)(nil).RollbackTx), ctx, tx)
}

// MockUserDatabase is a mock of UserDatabase interface.
type MockUserDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockUserDatabaseMockRecorder
	isgomock struct{}
}

// MockUserDatabaseMockRecorder is the mock recorder for MockUserDatabase.
type MockUserDatabaseMockRecorder struct {
	mock *MockUserDatabase
}

// NewMockUserDatabase creates a new mock instance.
func NewMockUserDatabase(ctrl *gomock.Controller) *MockUserDatabase {
	mock := &MockUserDatabase{ctrl: ctrl}
	mock.recorder = &MockUserDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserDatabase) EXPECT() *MockUserDatabaseMockRecorder {
	return m.recorder
}

// AddUser mocks base method.
func (m *MockUserDatabase) AddUser(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockUserDatabaseMockRecorder) AddUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockUserDatabase)(nil).AddUser), ctx, user)
}

// MockStoryDatabase is a mock of StoryDatabase interface.
type MockStoryDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockStoryDatabaseMockRecorder
	isgomock struct{}
}

// MockStoryDatabaseMockRecorder is the mock recorder for MockStoryDatabase.
type MockStoryDatabaseMockRecorder struct {
	mock *MockStoryDatabase
}

// NewMockStoryDatabase creates a new mock instance.
func NewMockStoryDatabase(ctrl *gomock.Controller) *MockStoryDatabase {
	mock := &MockStoryDatabase{ctrl: ctrl}
	mock.recorder = &MockStoryDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoryDatabase) EXPECT() *MockStoryDatabaseMockRecorder {
	return m.recorder
}

// AddStory mocks base method.
func (m *MockStoryDatabase) AddStory(ctx context.Context, tx pgx.Tx, story *models.Story) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStory", ctx, tx, story)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddStory indicates an expected call of AddStory.
func (mr *MockStoryDatabaseMockRecorder) AddStory(ctx, tx, story any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStory", reflect.TypeOf((*MockStoryDatabase)(nil).AddStory), ctx, tx, story)
}

// GetActiveStories mocks base method.
func (m *MockStoryDatabase) GetActiveStories(ctx context.Context, userID int64) ([]*models.Story, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveStories", ctx, userID)
	ret0, _ := ret[0].([]*models.Story)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveStories indicates an expected call of GetActiveStories.
func (mr *MockStoryDatabaseMockRecorder) GetActiveStories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveStories", reflect.TypeOf((*MockStoryDatabase)(nil).GetActiveStories), ctx, userID)
}

// StopStory mocks base method.
func (m *MockStoryDatabase) StopStory(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopStory", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopStory indicates an expected call of StopStory.
func (mr *MockStoryDatabaseMockRecorder) StopStory(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopStory", reflect.TypeOf((*MockStoryDatabase)(nil).StopStory), ctx, userID)
}

// MockVariantDatabase is a mock of VariantDatabase interface.
type MockVariantDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockVariantDatabaseMockRecorder
	isgomock struct{}
}

// MockVariantDatabaseMockRecorder is the mock recorder for MockVariantDatabase.
type MockVariantDatabaseMockRecorder struct {
	mock *MockVariantDatabase
}

// NewMockVariantDatabase creates a new mock instance.
func NewMockVariantDatabase(ctrl *gomock.Controller) *MockVariantDatabase {
	mock := &MockVariantDatabase{ctrl: ctrl}
	mock.recorder = &MockVariantDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVariantDatabase) EXPECT() *MockVariantDatabaseMockRecorder {
	return m.recorder
}

// AddVariant mocks base method.
func (m *MockVariantDatabase) AddVariant(ctx context.Context, tx pgx.Tx, variant *models.StoryVariant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddVariant", ctx, tx, variant)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddVariant indicates an expected call of AddVariant.
func (mr *MockVariantDatabaseMockRecorder) AddVariant(ctx, tx, variant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVariant", reflect.TypeOf((*MockVariantDatabase)(nil).AddVariant), ctx, tx, variant)
}

// GetActiveVariants mocks base method.
func (m *MockVariantDatabase) GetActiveVariants(ctx context.Context, userID int64) ([]*models.StoryVariant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveVariants", ctx, userID)
	ret0, _ := ret[0].([]*models.StoryVariant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveVariants indicates an expected call of GetActiveVariants.
func (mr *MockVariantDatabaseMockRecorder) GetActiveVariants(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveVariants", reflect.TypeOf((*MockVariantDatabase)(nil).GetActiveVariants), ctx, userID)
}

// UpdateVariant mocks base method.
func (m *MockVariantDatabase) UpdateVariant(ctx context.Context, tx pgx.Tx, variant *models.StoryVariant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariant", ctx, tx, variant)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVariant indicates an expected call of UpdateVariant.
func (mr *MockVariantDatabaseMockRecorder) UpdateVariant(ctx, tx, variant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariant", reflect.TypeOf((*MockVariantDatabase)(nil).UpdateVariant), ctx, tx, variant)
}

// MockDailyLimitDatabase is a mock of DailyLimitDatabase interface.
type MockDailyLimitDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDailyLimitDatabaseMockRecorder
	isgomock struct{}
}

// MockDailyLimitDatabaseMockRecorder is the mock recorder for MockDailyLimitDatabase.
type MockDailyLimitDatabaseMockRecorder struct {
	mock *MockDailyLimitDatabase
}

// NewMockDailyLimitDatabase creates a new mock instance.
func NewMockDailyLimitDatabase(ctrl *gomock.Controller) *MockDailyLimitDatabase {
	mock := &MockDailyLimitDatabase{ctrl: ctrl}
	mock.recorder = &MockDailyLimitDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDailyLimitDatabase) EXPECT() *MockDailyLimitDatabaseMockRecorder {
	return m.recorder
}

// AddDailyLimit mocks base method.
func (m *MockDailyLimitDatabase) AddDailyLimit(ctx context.Context, tx pgx.Tx, dailyLimit *models.DailyLimit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDailyLimit", ctx, tx, dailyLimit)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDailyLimit indicates an expected call of AddDailyLimit.
func (mr *MockDailyLimitDatabaseMockRecorder) AddDailyLimit(ctx, tx, dailyLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDailyLimit", reflect.TypeOf((*MockDailyLimitDatabase)(nil).AddDailyLimit), ctx, tx, dailyLimit)
}

// GetDailyLimit mocks base method.
func (m *MockDailyLimitDatabase) GetDailyLimit(ctx context.Context, userID int64) (*models.DailyLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyLimit", ctx, userID)
	ret0, _ := ret[0].(*models.DailyLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyLimit indicates an expected call of GetDailyLimit.
func (mr *MockDailyLimitDatabaseMockRecorder) GetDailyLimit(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyLimit", reflect.TypeOf((*MockDailyLimitDatabase)(nil).GetDailyLimit), ctx, userID)
}

// UpdateCountDailyLimit mocks base method.
func (m *MockDailyLimitDatabase) UpdateCountDailyLimit(ctx context.Context, tx pgx.Tx, dailyLimit *models.DailyLimit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCountDailyLimit", ctx, tx, dailyLimit)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCountDailyLimit indicates an expected call of UpdateCountDailyLimit.
func (mr *MockDailyLimitDatabaseMockRecorder) UpdateCountDailyLimit(ctx, tx, dailyLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCountDailyLimit", reflect.TypeOf((*MockDailyLimitDatabase)(nil).UpdateCountDailyLimit), ctx, tx, dailyLimit)
}

// UpdateLimitCountDailyLimit mocks base method.
func (m *MockDailyLimitDatabase) UpdateLimitCountDailyLimit(ctx context.Context, dailyLimit *models.DailyLimit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLimitCountDailyLimit", ctx, dailyLimit)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLimitCountDailyLimit indicates an expected call of UpdateLimitCountDailyLimit.
func (mr *MockDailyLimitDatabaseMockRecorder) UpdateLimitCountDailyLimit(ctx, dailyLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLimitCountDailyLimit", reflect.TypeOf((*MockDailyLimitDatabase)(nil).UpdateLimitCountDailyLimit), ctx, dailyLimit)
}

// MockMessageDatabase is a mock of MessageDatabase interface.
type MockMessageDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockMessageDatabaseMockRecorder
	isgomock struct{}
}

// MockMessageDatabaseMockRecorder is the mock recorder for MockMessageDatabase.
type MockMessageDatabaseMockRecorder struct {
	mock *MockMessageDatabase
}

// NewMockMessageDatabase creates a new mock instance.
func NewMockMessageDatabase(ctrl *gomock.Controller) *MockMessageDatabase {
	mock := &MockMessageDatabase{ctrl: ctrl}
	mock.recorder = &MockMessageDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageDatabase) EXPECT() *MockMessageDatabaseMockRecorder {
	return m.recorder
}

// AddStoryMessages mocks base method.
func (m *MockMessageDatabase) AddStoryMessages(ctx context.Context, tx pgx.Tx, msgs []*models.StoryMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStoryMessages", ctx, tx, msgs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddStoryMessages indicates an expected call of AddStoryMessages.
func (mr *MockMessageDatabaseMockRecorder) AddStoryMessages(ctx, tx, msgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStoryMessages", reflect.TypeOf((*MockMessageDatabase)(nil).AddStoryMessages), ctx, tx, msgs)
}

// GetAllStorySegments mocks base method.
func (m *MockMessageDatabase) GetAllStorySegments(ctx context.Context, storyID int) ([]*models.StoryMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStorySegments", ctx, storyID)
	ret0, _ := ret[0].([]*models.StoryMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStorySegments indicates an expected call of GetAllStorySegments.
func (mr *MockMessageDatabaseMockRecorder) GetAllStorySegments(ctx, storyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStorySegments", reflect.TypeOf((*MockMessageDatabase)(nil).GetAllStorySegments), ctx, storyID)
}

// MockSubscriptionDatabase is a mock of SubscriptionDatabase interface.
type MockSubscriptionDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionDatabaseMockRecorder
	isgomock struct{}
}

// MockSubscriptionDatabaseMockRecorder is the mock recorder for MockSubscriptionDatabase.
type MockSubscriptionDatabaseMockRecorder struct {
	mock *MockSubscriptionDatabase
}

// NewMockSubscriptionDatabase creates a new mock instance.
func NewMockSubscriptionDatabase(ctrl *gomock.Controller) *MockSubscriptionDatabase {
	mock := &MockSubscriptionDatabase{ctrl: ctrl}
	mock.recorder = &MockSubscriptionDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionDatabase) EXPECT() *MockSubscriptionDatabaseMockRecorder {
	return m.recorder
}

// AddSubscription mocks base method.
func (m *MockSubscriptionDatabase) AddSubscription(ctx context.Context, subscription *models.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSubscription", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddSubscription indicates an expected call of AddSubscription.
func (mr *MockSubscriptionDatabaseMockRecorder) AddSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSubscription", reflect.TypeOf((*MockSubscriptionDatabase)(nil).AddSubscription), ctx, subscription)
}

// GetActiveSubscriptions mocks base method.
func (m *MockSubscriptionDatabase) GetActiveSubscriptions(ctx context.Context, userID int64) ([]*models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveSubscriptions", ctx, userID)
	ret0, _ := ret[0].([]*models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveSubscriptions indicates an expected call of GetActiveSubscriptions.
func (mr *MockSubscriptionDatabaseMockRecorder) GetActiveSubscriptions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveSubscriptions", reflect.TypeOf((*MockSubscriptionDatabase)(nil).GetActiveSubscriptions), ctx, userID)
}

// GetStatusSubscription mocks base method.
func (m *MockSubscriptionDatabase) GetStatusSubscription(ctx context.Context, payload string, userID int64) (*models.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusSubscription", ctx, payload, userID)
	ret0, _ := ret[0].(*models.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusSubscription indicates an expected call of GetStatusSubscription.
func (mr *MockSubscriptionDatabaseMockRecorder) GetStatusSubscription(ctx, payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusSubscription", reflect.TypeOf((*MockSubscriptionDatabase)(nil).GetStatusSubscription), ctx, payload, userID)
}

// PayedPendingSubscription mocks base method.
func (m *MockSubscriptionDatabase) PayedPendingSubscription(ctx context.Context, payload string, userID int64, start, end time.Time, changeID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PayedPendingSubscription", ctx, payload, userID, start, end, changeID)
	ret0, _ := ret[0].(error)
	return ret0
}

// PayedPendingSubscription indicates an expected call of PayedPendingSubscription.
func (mr *MockSubscriptionDatabaseMockRecorder) PayedPendingSubscription(ctx, payload, userID, start, end, changeID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PayedPendingSubscription", reflect.TypeOf((*MockSubscriptionDatabase)(nil).PayedPendingSubscription), ctx, payload, userID, start, end, changeID)
}

// RejectedPendingSubscription mocks base method.
func (m *MockSubscriptionDatabase) RejectedPendingSubscription(ctx context.Context, payload string, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RejectedPendingSubscription", ctx, payload, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RejectedPendingSubscription indicates an expected call of RejectedPendingSubscription.
func (mr *MockSubscriptionDatabaseMockRecorder) RejectedPendingSubscription(ctx, payload, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RejectedPendingSubscription", reflect.TypeOf((*MockSubscriptionDatabase)(nil).RejectedPendingSubscription), ctx, payload, userID)
}

// UpdateSubscription mocks base method.
func (m *MockSubscriptionDatabase) UpdateSubscription(ctx context.Context, subscription *models.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubscription", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSubscription indicates an expected call of UpdateSubscription.
func (mr *MockSubscriptionDatabaseMockRecorder) UpdateSubscription(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubscription", reflect.TypeOf((*MockSubscriptionDatabase)(nil).UpdateSubscription), ctx, subscription)
}

// MockSettingDatabase is a mock of SettingDatabase interface.
type MockSettingDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockSettingDatabaseMockRecorder
	isgomock struct{}
}

// MockSettingDatabaseMockRecorder is the mock recorder for MockSettingDatabase.
type MockSettingDatabaseMockRecorder struct {
	mock *MockSettingDatabase
}

// NewMockSettingDatabase creates a new mock instance.
func NewMockSettingDatabase(ctrl *gomock.Controller) *MockSettingDatabase {
	mock := &MockSettingDatabase{ctrl: ctrl}
	mock.recorder = &MockSettingDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingDatabase) EXPECT() *MockSettingDatabaseMockRecorder {
	return m.recorder
}

// GetAllSettings mocks base method.
func (m *MockSettingDatabase) GetAllSettings(ctx context.Context) ([]*models.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSettings", ctx)
	ret0, _ := ret[0].([]*models.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSettings indicates an expected call of GetAllSettings.
func (mr *MockSettingDatabaseMockRecorder) GetAllSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSettings", reflect.TypeOf((*MockSettingDatabase)(nil).GetAllSettings), ctx)
}

// GetSetting mocks base method.
func (m *MockSettingDatabase) GetSetting(ctx context.Context, key string) (*models.Setting, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetting", ctx, key)
	ret0, _ := ret[0].(*models.Setting)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetting indicates an expected call of GetSetting.
func (mr *MockSettingDatabaseMockRecorder) GetSetting(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetting", reflect.TypeOf((*MockSettingDatabase)(nil).GetSetting), ctx, key)
}

// SetSetting mocks base method.
func (m *MockSettingDatabase) SetSetting(ctx context.Context, tx pgx.Tx, setting *models.Setting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSetting", ctx, tx, setting)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSetting indicates an expected call of SetSetting.
func (mr *MockSettingDatabaseMockRecorder) SetSetting(ctx, tx, setting any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSetting", reflect.TypeOf((*MockSettingDatabase)(nil).SetSetting), ctx, tx, setting)
}

// MockStoryAI is a mock of StoryAI interface.
type MockStoryAI struct {
	ctrl     *gomock.Controller
	recorder *MockStoryAIMockRecorder
	isgomock struct{}
}

// MockStoryAIMockRecorder is the mock recorder for MockStoryAI.
type MockStoryAIMockRecorder struct {
	mock *MockStoryAI
}

// NewMockStoryAI creates a new mock instance.
func NewMockStoryAI(ctrl *gomock.Controller) *MockStoryAI {
	mock := &MockStoryAI{ctrl: ctrl}
	mock.recorder = &MockStoryAIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoryAI) EXPECT() *MockStoryAIMockRecorder {
	return m.recorder
}

// GenerateNextStorySegment mocks base method.
func (m *MockStoryAI) GenerateNextStorySegment(parctx context.Context, storyData []*models.StoryMessage) (*models.StoryNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateNextStorySegment", parctx, storyData)
	ret0, _ := ret[0].(*models.StoryNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateNextStorySegment indicates an expected call of GenerateNextStorySegment.
func (mr *MockStoryAIMockRecorder) GenerateNextStorySegment(parctx, storyData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNextStorySegment", reflect.TypeOf((*MockStoryAI)(nil).GenerateNextStorySegment), parctx, storyData)
}

// GetStructuredHeroes mocks base method.
func (m *MockStoryAI) GetStructuredHeroes(ctx context.Context) (*models.FantasyCharacters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructuredHeroes", ctx)
	ret0, _ := ret[0].(*models.FantasyCharacters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStructuredHeroes indicates an expected call of GetStructuredHeroes.
func (mr *MockStoryAIMockRecorder) GetStructuredHeroes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructuredHeroes", reflect.TypeOf((*MockStoryAI)(nil).GetStructuredHeroes), ctx)
}

// MockDailyLimitCache is a mock of DailyLimitCache interface.
type MockDailyLimitCache struct {
	ctrl     *gomock.Controller
	recorder *MockDailyLimitCacheMockRecorder
	isgomock struct{}
}

// MockDailyLimitCacheMockRecorder is the mock recorder for MockDailyLimitCache.
type MockDailyLimitCacheMockRecorder struct {
	mock *MockDailyLimitCache
}

// NewMockDailyLimitCache creates a new mock instance.
func NewMockDailyLimitCache(ctrl *gomock.Controller) *MockDailyLimitCache {
	mock := &MockDailyLimitCache{ctrl: ctrl}
	mock.recorder = &MockDailyLimitCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDailyLimitCache) EXPECT() *MockDailyLimitCacheMockRecorder {
	return m.recorder
}

// AddExceededLimit mocks base method.
func (m *MockDailyLimitCache) AddExceededLimit(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddExceededLimit", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddExceededLimit indicates an expected call of AddExceededLimit.
func (mr *MockDailyLimitCacheMockRecorder) AddExceededLimit(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExceededLimit", reflect.TypeOf((*MockDailyLimitCache)(nil).AddExceededLimit), ctx, userID)
}

// CheckExceededLimit mocks base method.
func (m *MockDailyLimitCache) CheckExceededLimit(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExceededLimit", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExceededLimit indicates an expected call of CheckExceededLimit.
func (mr *MockDailyLimitCacheMockRecorder) CheckExceededLimit(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExceededLimit", reflect.TypeOf((*MockDailyLimitCache)(nil).CheckExceededLimit), ctx, userID)
}

// DeleteExceededLimit mocks base method.
func (m *MockDailyLimitCache) DeleteExceededLimit(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExceededLimit", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExceededLimit indicates an expected call of DeleteExceededLimit.
func (mr *MockDailyLimitCacheMockRecorder) DeleteExceededLimit(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExceededLimit", reflect.TypeOf((*MockDailyLimitCache)(nil).DeleteExceededLimit), ctx, userID)
}

// MockSettingCache is a mock of SettingCache interface.
type MockSettingCache struct {
	ctrl     *gomock.Controller
	recorder *MockSettingCacheMockRecorder
	isgomock struct{}
}

// MockSettingCacheMockRecorder is the mock recorder for MockSettingCache.
type MockSettingCacheMockRecorder struct {
	mock *MockSettingCache
}

// NewMockSettingCache creates a new mock instance.
func NewMockSettingCache(ctrl *gomock.Controller) *MockSettingCache {
	mock := &MockSettingCache{ctrl: ctrl}
	mock.recorder = &MockSettingCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingCache) EXPECT() *MockSettingCacheMockRecorder {
	return m.recorder
}

// GetAllSettings mocks base method.
func (m *MockSettingCache) GetAllSettings(ctx context.Context) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSettings", ctx)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSettings indicates an expected call of GetAllSettings.
func (mr *MockSettingCacheMockRecorder) GetAllSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSettings", reflect.TypeOf((*MockSettingCache)(nil).GetAllSettings), ctx)
}

// GetSetting mocks base method.
func (m *MockSettingCache) GetSetting(ctx context.Context, key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSetting", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSetting indicates an expected call of GetSetting.
func (mr *MockSettingCacheMockRecorder) GetSetting(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSetting", reflect.TypeOf((*MockSettingCache)(nil).GetSetting), ctx, key)
}

// LoadCacheData mocks base method.
func (m *MockSettingCache) LoadCacheData(ctx context.Context, settings []*models.Setting) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadCacheData", ctx, settings)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadCacheData indicates an expected call of LoadCacheData.
func (mr *MockSettingCacheMockRecorder) LoadCacheData(ctx, settings any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadCacheData", reflect.TypeOf((*MockSettingCache)(nil).LoadCacheData), ctx, settings)
}

// SetSetting mocks base method.
func (m *MockSettingCache) SetSetting(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSetting", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSetting indicates an expected call of SetSetting.
func (mr *MockSettingCacheMockRecorder) SetSetting(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSetting", reflect.TypeOf((*MockSettingCache)(nil).SetSetting), ctx, key, value)
}

// MockUserCache is a mock of UserCache interface.
type MockUserCache struct {
	ctrl     *gomock.Controller
	recorder *MockUserCacheMockRecorder
	isgomock struct{}
}

// MockUserCacheMockRecorder is the mock recorder for MockUserCache.
type MockUserCacheMockRecorder struct {
	mock *MockUserCache
}

// NewMockUserCache creates a new mock instance.
func NewMockUserCache(ctrl *gomock.Controller) *MockUserCache {
	mock := &MockUserCache{ctrl: ctrl}
	mock.recorder = &MockUserCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCache) EXPECT() *MockUserCacheMockRecorder {
	return m.recorder
}

// AddCreatedUser mocks base method.
func (m *MockUserCache) AddCreatedUser(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCreatedUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCreatedUser indicates an expected call of AddCreatedUser.
func (mr *MockUserCacheMockRecorder) AddCreatedUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCreatedUser", reflect.TypeOf((*MockUserCache)(nil).AddCreatedUser), ctx, userID)
}

// CheckCreatedUser mocks base method.
func (m *MockUserCache) CheckCreatedUser(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCreatedUser", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCreatedUser indicates an expected call of CheckCreatedUser.
func (mr *MockUserCacheMockRecorder) CheckCreatedUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCreatedUser", reflect.TypeOf((*MockUserCache)(nil).CheckCreatedUser), ctx, userID)
}
