// Code generated by MockGen. DO NOT EDIT.
// Source: story_service.go
//
// Generated by this command:
//
//	mockgen -source=story_service.go -destination=mocks/mock.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	models "bot_story_generator/internal/models"
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockStoryDatabase is a mock of StoryDatabase interface.
type MockStoryDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockStoryDatabaseMockRecorder
	isgomock struct{}
}

// MockStoryDatabaseMockRecorder is the mock recorder for MockStoryDatabase.
type MockStoryDatabaseMockRecorder struct {
	mock *MockStoryDatabase
}

// NewMockStoryDatabase creates a new mock instance.
func NewMockStoryDatabase(ctrl *gomock.Controller) *MockStoryDatabase {
	mock := &MockStoryDatabase{ctrl: ctrl}
	mock.recorder = &MockStoryDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoryDatabase) EXPECT() *MockStoryDatabaseMockRecorder {
	return m.recorder
}

// AddStory mocks base method.
func (m *MockStoryDatabase) AddStory(ctx context.Context, tx pgx.Tx, story *models.Story) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStory", ctx, tx, story)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddStory indicates an expected call of AddStory.
func (mr *MockStoryDatabaseMockRecorder) AddStory(ctx, tx, story any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStory", reflect.TypeOf((*MockStoryDatabase)(nil).AddStory), ctx, tx, story)
}

// AddUser mocks base method.
func (m *MockStoryDatabase) AddUser(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockStoryDatabaseMockRecorder) AddUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockStoryDatabase)(nil).AddUser), ctx, user)
}

// AddVariant mocks base method.
func (m *MockStoryDatabase) AddVariant(ctx context.Context, tx pgx.Tx, variant *models.StoryVariant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddVariant", ctx, tx, variant)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddVariant indicates an expected call of AddVariant.
func (mr *MockStoryDatabaseMockRecorder) AddVariant(ctx, tx, variant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVariant", reflect.TypeOf((*MockStoryDatabase)(nil).AddVariant), ctx, tx, variant)
}

// BeginTx mocks base method.
func (m *MockStoryDatabase) BeginTx(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockStoryDatabaseMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockStoryDatabase)(nil).BeginTx), ctx)
}

// CheckActiveStories mocks base method.
func (m *MockStoryDatabase) CheckActiveStories(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckActiveStories", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckActiveStories indicates an expected call of CheckActiveStories.
func (mr *MockStoryDatabaseMockRecorder) CheckActiveStories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckActiveStories", reflect.TypeOf((*MockStoryDatabase)(nil).CheckActiveStories), ctx, userID)
}

// CommitTx mocks base method.
func (m *MockStoryDatabase) CommitTx(ctx context.Context, tx pgx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTx", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTx indicates an expected call of CommitTx.
func (mr *MockStoryDatabaseMockRecorder) CommitTx(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTx", reflect.TypeOf((*MockStoryDatabase)(nil).CommitTx), ctx, tx)
}

// GetAllStorySegments mocks base method.
func (m *MockStoryDatabase) GetAllStorySegments(ctx context.Context, chatID int64) (*models.AllStorySegments, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStorySegments", ctx, chatID)
	ret0, _ := ret[0].(*models.AllStorySegments)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStorySegments indicates an expected call of GetAllStorySegments.
func (mr *MockStoryDatabaseMockRecorder) GetAllStorySegments(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStorySegments", reflect.TypeOf((*MockStoryDatabase)(nil).GetAllStorySegments), ctx, chatID)
}

// RollbackTx mocks base method.
func (m *MockStoryDatabase) RollbackTx(ctx context.Context, tx pgx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTx", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTx indicates an expected call of RollbackTx.
func (mr *MockStoryDatabaseMockRecorder) RollbackTx(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTx", reflect.TypeOf((*MockStoryDatabase)(nil).RollbackTx), ctx, tx)
}

// MockStoryAI is a mock of StoryAI interface.
type MockStoryAI struct {
	ctrl     *gomock.Controller
	recorder *MockStoryAIMockRecorder
	isgomock struct{}
}

// MockStoryAIMockRecorder is the mock recorder for MockStoryAI.
type MockStoryAIMockRecorder struct {
	mock *MockStoryAI
}

// NewMockStoryAI creates a new mock instance.
func NewMockStoryAI(ctrl *gomock.Controller) *MockStoryAI {
	mock := &MockStoryAI{ctrl: ctrl}
	mock.recorder = &MockStoryAIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoryAI) EXPECT() *MockStoryAIMockRecorder {
	return m.recorder
}

// GenerateNextStorySegment mocks base method.
func (m *MockStoryAI) GenerateNextStorySegment(parctx context.Context, storyData string) (*models.StoryNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateNextStorySegment", parctx, storyData)
	ret0, _ := ret[0].(*models.StoryNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateNextStorySegment indicates an expected call of GenerateNextStorySegment.
func (mr *MockStoryAIMockRecorder) GenerateNextStorySegment(parctx, storyData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNextStorySegment", reflect.TypeOf((*MockStoryAI)(nil).GenerateNextStorySegment), parctx, storyData)
}

// GetChatCompletion mocks base method.
func (m *MockStoryAI) GetChatCompletion(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChatCompletion", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChatCompletion indicates an expected call of GetChatCompletion.
func (mr *MockStoryAIMockRecorder) GetChatCompletion(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChatCompletion", reflect.TypeOf((*MockStoryAI)(nil).GetChatCompletion), ctx)
}

// GetStructuredHeroes mocks base method.
func (m *MockStoryAI) GetStructuredHeroes(ctx context.Context) (*models.FantasyCharacters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructuredHeroes", ctx)
	ret0, _ := ret[0].(*models.FantasyCharacters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStructuredHeroes indicates an expected call of GetStructuredHeroes.
func (mr *MockStoryAIMockRecorder) GetStructuredHeroes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructuredHeroes", reflect.TypeOf((*MockStoryAI)(nil).GetStructuredHeroes), ctx)
}
