// Code generated by MockGen. DO NOT EDIT.
// Source: story_service.go
//
// Generated by this command:
//
//	mockgen -source=story_service.go -destination=mocks/mock.go
//

// Package mock_service is a generated GoMock package.
package mock_service

import (
	models "bot_story_generator/internal/models"
	context "context"
	reflect "reflect"

	pgx "github.com/jackc/pgx/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockStoryDatabase is a mock of StoryDatabase interface.
type MockStoryDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockStoryDatabaseMockRecorder
	isgomock struct{}
}

// MockStoryDatabaseMockRecorder is the mock recorder for MockStoryDatabase.
type MockStoryDatabaseMockRecorder struct {
	mock *MockStoryDatabase
}

// NewMockStoryDatabase creates a new mock instance.
func NewMockStoryDatabase(ctrl *gomock.Controller) *MockStoryDatabase {
	mock := &MockStoryDatabase{ctrl: ctrl}
	mock.recorder = &MockStoryDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoryDatabase) EXPECT() *MockStoryDatabaseMockRecorder {
	return m.recorder
}

// AddDailyLimit mocks base method.
func (m *MockStoryDatabase) AddDailyLimit(ctx context.Context, tx pgx.Tx, dailyLimit *models.DailyLimit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDailyLimit", ctx, tx, dailyLimit)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDailyLimit indicates an expected call of AddDailyLimit.
func (mr *MockStoryDatabaseMockRecorder) AddDailyLimit(ctx, tx, dailyLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDailyLimit", reflect.TypeOf((*MockStoryDatabase)(nil).AddDailyLimit), ctx, tx, dailyLimit)
}

// AddStory mocks base method.
func (m *MockStoryDatabase) AddStory(ctx context.Context, tx pgx.Tx, story *models.Story) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStory", ctx, tx, story)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddStory indicates an expected call of AddStory.
func (mr *MockStoryDatabaseMockRecorder) AddStory(ctx, tx, story any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStory", reflect.TypeOf((*MockStoryDatabase)(nil).AddStory), ctx, tx, story)
}

// AddStoryMessages mocks base method.
func (m *MockStoryDatabase) AddStoryMessages(ctx context.Context, tx pgx.Tx, msgs []*models.StoryMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStoryMessages", ctx, tx, msgs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddStoryMessages indicates an expected call of AddStoryMessages.
func (mr *MockStoryDatabaseMockRecorder) AddStoryMessages(ctx, tx, msgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStoryMessages", reflect.TypeOf((*MockStoryDatabase)(nil).AddStoryMessages), ctx, tx, msgs)
}

// AddUser mocks base method.
func (m *MockStoryDatabase) AddUser(ctx context.Context, user *models.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUser indicates an expected call of AddUser.
func (mr *MockStoryDatabaseMockRecorder) AddUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUser", reflect.TypeOf((*MockStoryDatabase)(nil).AddUser), ctx, user)
}

// AddVariant mocks base method.
func (m *MockStoryDatabase) AddVariant(ctx context.Context, tx pgx.Tx, variant *models.StoryVariant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddVariant", ctx, tx, variant)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddVariant indicates an expected call of AddVariant.
func (mr *MockStoryDatabaseMockRecorder) AddVariant(ctx, tx, variant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVariant", reflect.TypeOf((*MockStoryDatabase)(nil).AddVariant), ctx, tx, variant)
}

// BeginTx mocks base method.
func (m *MockStoryDatabase) BeginTx(ctx context.Context) (pgx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(pgx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockStoryDatabaseMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockStoryDatabase)(nil).BeginTx), ctx)
}

// CommitTx mocks base method.
func (m *MockStoryDatabase) CommitTx(ctx context.Context, tx pgx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTx", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTx indicates an expected call of CommitTx.
func (mr *MockStoryDatabaseMockRecorder) CommitTx(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTx", reflect.TypeOf((*MockStoryDatabase)(nil).CommitTx), ctx, tx)
}

// GetActiveStories mocks base method.
func (m *MockStoryDatabase) GetActiveStories(ctx context.Context, userID int64) ([]*models.Story, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveStories", ctx, userID)
	ret0, _ := ret[0].([]*models.Story)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveStories indicates an expected call of GetActiveStories.
func (mr *MockStoryDatabaseMockRecorder) GetActiveStories(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveStories", reflect.TypeOf((*MockStoryDatabase)(nil).GetActiveStories), ctx, userID)
}

// GetActiveVariants mocks base method.
func (m *MockStoryDatabase) GetActiveVariants(ctx context.Context, userID int64) ([]*models.StoryVariant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveVariants", ctx, userID)
	ret0, _ := ret[0].([]*models.StoryVariant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveVariants indicates an expected call of GetActiveVariants.
func (mr *MockStoryDatabaseMockRecorder) GetActiveVariants(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveVariants", reflect.TypeOf((*MockStoryDatabase)(nil).GetActiveVariants), ctx, userID)
}

// GetAllStorySegments mocks base method.
func (m *MockStoryDatabase) GetAllStorySegments(ctx context.Context, storyID int) ([]*models.StoryMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllStorySegments", ctx, storyID)
	ret0, _ := ret[0].([]*models.StoryMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllStorySegments indicates an expected call of GetAllStorySegments.
func (mr *MockStoryDatabaseMockRecorder) GetAllStorySegments(ctx, storyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllStorySegments", reflect.TypeOf((*MockStoryDatabase)(nil).GetAllStorySegments), ctx, storyID)
}

// GetDailyLimit mocks base method.
func (m *MockStoryDatabase) GetDailyLimit(ctx context.Context, userID int64) (*models.DailyLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyLimit", ctx, userID)
	ret0, _ := ret[0].(*models.DailyLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyLimit indicates an expected call of GetDailyLimit.
func (mr *MockStoryDatabaseMockRecorder) GetDailyLimit(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyLimit", reflect.TypeOf((*MockStoryDatabase)(nil).GetDailyLimit), ctx, userID)
}

// RollbackTx mocks base method.
func (m *MockStoryDatabase) RollbackTx(ctx context.Context, tx pgx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RollbackTx", ctx, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RollbackTx indicates an expected call of RollbackTx.
func (mr *MockStoryDatabaseMockRecorder) RollbackTx(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RollbackTx", reflect.TypeOf((*MockStoryDatabase)(nil).RollbackTx), ctx, tx)
}

// StopStory mocks base method.
func (m *MockStoryDatabase) StopStory(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopStory", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopStory indicates an expected call of StopStory.
func (mr *MockStoryDatabaseMockRecorder) StopStory(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopStory", reflect.TypeOf((*MockStoryDatabase)(nil).StopStory), ctx, userID)
}

// UpdateDailyLimit mocks base method.
func (m *MockStoryDatabase) UpdateDailyLimit(ctx context.Context, tx pgx.Tx, dailyLimit *models.DailyLimit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDailyLimit", ctx, tx, dailyLimit)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDailyLimit indicates an expected call of UpdateDailyLimit.
func (mr *MockStoryDatabaseMockRecorder) UpdateDailyLimit(ctx, tx, dailyLimit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDailyLimit", reflect.TypeOf((*MockStoryDatabase)(nil).UpdateDailyLimit), ctx, tx, dailyLimit)
}

// UpdateVariant mocks base method.
func (m *MockStoryDatabase) UpdateVariant(ctx context.Context, tx pgx.Tx, variant *models.StoryVariant) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVariant", ctx, tx, variant)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVariant indicates an expected call of UpdateVariant.
func (mr *MockStoryDatabaseMockRecorder) UpdateVariant(ctx, tx, variant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVariant", reflect.TypeOf((*MockStoryDatabase)(nil).UpdateVariant), ctx, tx, variant)
}

// MockStoryAI is a mock of StoryAI interface.
type MockStoryAI struct {
	ctrl     *gomock.Controller
	recorder *MockStoryAIMockRecorder
	isgomock struct{}
}

// MockStoryAIMockRecorder is the mock recorder for MockStoryAI.
type MockStoryAIMockRecorder struct {
	mock *MockStoryAI
}

// NewMockStoryAI creates a new mock instance.
func NewMockStoryAI(ctrl *gomock.Controller) *MockStoryAI {
	mock := &MockStoryAI{ctrl: ctrl}
	mock.recorder = &MockStoryAIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoryAI) EXPECT() *MockStoryAIMockRecorder {
	return m.recorder
}

// GenerateNextStorySegment mocks base method.
func (m *MockStoryAI) GenerateNextStorySegment(parctx context.Context, storyData []*models.StoryMessage) (*models.StoryNode, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateNextStorySegment", parctx, storyData)
	ret0, _ := ret[0].(*models.StoryNode)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateNextStorySegment indicates an expected call of GenerateNextStorySegment.
func (mr *MockStoryAIMockRecorder) GenerateNextStorySegment(parctx, storyData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateNextStorySegment", reflect.TypeOf((*MockStoryAI)(nil).GenerateNextStorySegment), parctx, storyData)
}

// GetStructuredHeroes mocks base method.
func (m *MockStoryAI) GetStructuredHeroes(ctx context.Context) (*models.FantasyCharacters, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStructuredHeroes", ctx)
	ret0, _ := ret[0].(*models.FantasyCharacters)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStructuredHeroes indicates an expected call of GetStructuredHeroes.
func (mr *MockStoryAIMockRecorder) GetStructuredHeroes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStructuredHeroes", reflect.TypeOf((*MockStoryAI)(nil).GetStructuredHeroes), ctx)
}

// MockStoryCache is a mock of StoryCache interface.
type MockStoryCache struct {
	ctrl     *gomock.Controller
	recorder *MockStoryCacheMockRecorder
	isgomock struct{}
}

// MockStoryCacheMockRecorder is the mock recorder for MockStoryCache.
type MockStoryCacheMockRecorder struct {
	mock *MockStoryCache
}

// NewMockStoryCache creates a new mock instance.
func NewMockStoryCache(ctrl *gomock.Controller) *MockStoryCache {
	mock := &MockStoryCache{ctrl: ctrl}
	mock.recorder = &MockStoryCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStoryCache) EXPECT() *MockStoryCacheMockRecorder {
	return m.recorder
}

// AddCreatedUser mocks base method.
func (m *MockStoryCache) AddCreatedUser(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCreatedUser", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCreatedUser indicates an expected call of AddCreatedUser.
func (mr *MockStoryCacheMockRecorder) AddCreatedUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCreatedUser", reflect.TypeOf((*MockStoryCache)(nil).AddCreatedUser), ctx, userID)
}

// AddExceededLimit mocks base method.
func (m *MockStoryCache) AddExceededLimit(ctx context.Context, userID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddExceededLimit", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddExceededLimit indicates an expected call of AddExceededLimit.
func (mr *MockStoryCacheMockRecorder) AddExceededLimit(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddExceededLimit", reflect.TypeOf((*MockStoryCache)(nil).AddExceededLimit), ctx, userID)
}

// CheckCreatedUser mocks base method.
func (m *MockStoryCache) CheckCreatedUser(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckCreatedUser", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckCreatedUser indicates an expected call of CheckCreatedUser.
func (mr *MockStoryCacheMockRecorder) CheckCreatedUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckCreatedUser", reflect.TypeOf((*MockStoryCache)(nil).CheckCreatedUser), ctx, userID)
}

// CheckExceededLimit mocks base method.
func (m *MockStoryCache) CheckExceededLimit(ctx context.Context, userID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckExceededLimit", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckExceededLimit indicates an expected call of CheckExceededLimit.
func (mr *MockStoryCacheMockRecorder) CheckExceededLimit(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckExceededLimit", reflect.TypeOf((*MockStoryCache)(nil).CheckExceededLimit), ctx, userID)
}
